# Generated by Django 3.2.20 on 2023-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
