# Generated by Django 3.2.20 on 2023-12-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0012_lesson_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Topic_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=50)),
                ('lesson_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='ebooks/pdfs/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_lessons', to='ebook.ebook')),
            ],
        ),
    ]
